### ISSUE TITLE
Magic style: vertical-align: -.125em;

### ISSUE THREAD

**Issue by HeskeyBaozi** [ant-design/ant-design-icons#7]
`SVG`图标与文字在一起的时候，`SVG`图标不会与行的基线对齐。
必须设置如下样式才能对齐。
```css
svg {
   vertical-align: -.125em;
}
```
See https://blog.prototypr.io/align-svg-icons-to-text-and-say-goodbye-to-font-icons-d44b3d7b26b4

考虑这一特性。
是否需要适配器如`@ant-design/icons-react`中帮用户设置好此样式？
还是需要用户自行设置？如`antd`里的`.anticon`类中设置了`vertical-align: -.125em;`。
